import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {BookOpen,BrainCircuit,ChevronRight,Edit3,Plus,Search,Trash2,X,Trophy,LayoutDashboard} from 'lucide-react';
import './styles.css';
const API='http://127.0.0.1:8000';
function App(){
 const [topics,setTopics]=useState([]),[questions,setQuestions]=useState([]),[active,setActive]=useState(null),[view,setView]=useState('dashboard'),[search,setSearch]=useState(''),[modal,setModal]=useState(null),[form,setForm]=useState({}),[ai,setAi]=useState('');
 const loadTopics=()=>fetch(API+'/api/topics').then(r=>r.json()).then(setTopics);
 const loadQuestions=(id=active?.id)=>id&&fetch(`${API}/api/questions?topic_id=${id}`).then(r=>r.json()).then(setQuestions);
 useEffect(()=>{loadTopics()},[]); useEffect(()=>{if(active)loadQuestions(active.id)},[active]);
 const saveTopic=async()=>{await fetch(API+`/api/topics${modal==='editTopic'?'/'+form.id:''}`,{method:modal==='editTopic'?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});setModal(null);loadTopics()};
 const deleteTopic=async id=>{if(confirm('Delete this topic and all its questions?')){await fetch(API+'/api/topics/'+id,{method:'DELETE'});if(active?.id===id){setActive(null);setView('dashboard')}loadTopics()}};
 const saveQuestion=async()=>{await fetch(API+`/api/questions${modal==='editQuestion'?'/'+form.id:''}`,{method:modal==='editQuestion'?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,topic_id:active.id})});setModal(null);loadQuestions()};
 const deleteQuestion=async id=>{if(confirm('Delete this question?')){await fetch(API+'/api/questions/'+id,{method:'DELETE'});loadQuestions()}};
 const generate=async()=>{setAi('Generating with Ollama...');let r=await fetch(API+'/api/ai/generate/'+encodeURIComponent(active.name),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({count:5,difficulty:'Medium',category:'Interview'})});let d=await r.json();setAi(d.content||d.detail||'');};
 return <div className="app"><aside><div className="logo"><BrainCircuit/> <b>KapilAI</b></div><button onClick={()=>{setView('dashboard');setActive(null)}}><LayoutDashboard/> Dashboard</button><button onClick={()=>setView('topics')}><BookOpen/> Topics</button><button onClick={()=>setView('mock')}><Trophy/> Mock Test</button><div className="sideFoot">Interview Preparation Hub<br/><small>kapilai.com</small></div></aside><main><header><div><h1>{active?active.icon+' '+active.name:'KapilAI'}</h1><p>{active?'Topic-wise interview questions':'Prepare smarter. Practice better.'}</p></div><div className="search"><Search size={17}/><input placeholder="Search questions..." value={search} onChange={e=>setSearch(e.target.value)}/></div></header>
 {view==='dashboard'&&!active&&<Dashboard topics={topics} open={t=>{setActive(t);setView('topic')}}/>}
 {view==='topics'&&!active&&<Topics topics={topics} open={t=>{setActive(t);setView('topic')}} add={()=>{setForm({name:'',description:'',icon:'📚'});setModal('addTopic')}} edit={t=>{setForm(t);setModal('editTopic')}} del={deleteTopic}/>} 
 {view==='topic'&&active&&<section><div className="actions"><button className="primary" onClick={()=>{setForm({question:'',answer:'',difficulty:'Medium',category:'Interview',tags:''});setModal('addQuestion')}}><Plus/> Add Question</button><button className="aiBtn" onClick={generate}><BrainCircuit/> Generate with Ollama</button><button onClick={()=>setView('mock')}><Trophy/> Mock Test</button></div>{ai&&<pre className="aiBox">{ai}</pre>}<div className="questionList">{questions.filter(q=>(q.question+' '+q.tags).toLowerCase().includes(search.toLowerCase())).map((q,i)=><article className="question" key={q.id}><span className="num">{i+1}</span><div><h3>{q.question}</h3><p>{q.answer||'Answer not added yet.'}</p><div className="meta"><span>{q.difficulty}</span><span>{q.category}</span>{q.tags&&<span>{q.tags}</span>}</div></div><div className="qactions"><button onClick={()=>{setForm(q);setModal('editQuestion')}}><Edit3 size={16}/></button><button onClick={()=>deleteQuestion(q.id)}><Trash2 size={16}/></button></div></article>)}</div></section>}
 {view==='mock'&&<Mock topics={topics} active={active}/>} 
 {modal&&<Modal modal={modal} form={form} setForm={setForm} close={()=>setModal(null)} save={modal.includes('Topic')?saveTopic:saveQuestion}/>}</main></div>}
function Dashboard({topics,open}){return <section><div className="hero"><div><span className="pill">AI-POWERED INTERVIEW HUB</span><h2>Master your interview.<br/><em>One topic at a time.</em></h2><p>Manage questions, practice topic-wise and use local Ollama AI when you need it.</p></div><BrainCircuit size={90}/></div><div className="stats"><Card n={topics.length} t="Topics"/><Card n="—" t="Questions"/><Card n="—" t="Mock Tests"/><Card n="AI" t="Ollama"/></div><h2 className="sectionTitle">Learning Roadmap</h2><div className="topicGrid">{topics.map(t=><div className="topicCard" onClick={()=>open(t)} key={t.id}><div className="icon">{t.icon}</div><h3>{t.name}</h3><p>{t.description}</p><ChevronRight/></div>)}</div></section>}
const Card=({n,t})=><div className="stat"><b>{n}</b><span>{t}</span></div>;
function Topics({topics,open,add,edit,del}){return <section><div className="pageTitle"><div><h2>Topics</h2><p>Add, update and delete your interview preparation topics.</p></div><button className="primary" onClick={add}><Plus/> Add Topic</button></div><div className="topicGrid">{topics.map(t=><div className="topicCard" key={t.id}><div onClick={()=>open(t)}><div className="icon">{t.icon}</div><h3>{t.name}</h3><p>{t.description}</p></div><div className="cardBtns"><button onClick={()=>edit(t)}><Edit3 size={15}/></button><button onClick={()=>del(t.id)}><Trash2 size={15}/></button></div></div>)}</div></section>}
function Mock({topics,active}){const [topic,setTopic]=useState(active?.id||topics[0]?.id||'');const [qs,setQs]=useState([]);const [i,setI]=useState(0);const [started,setStarted]=useState(false);const [done,setDone]=useState(false);const start=async()=>{let r=await fetch(`${API}/api/questions?topic_id=${topic}`);let d=await r.json();setQs(d.sort(()=>Math.random()-.5).slice(0,10));setStarted(true)};return <section className="mock"><div className="mockCard"><Trophy size={42}/><h2>Topic-wise Mock Test</h2>{!started?<><select value={topic} onChange={e=>setTopic(e.target.value)}>{topics.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select><button className="primary" onClick={start}>Start Mock Test</button></>:done?<><h2>Test Completed 🎉</h2><p>Review your answers and practice again.</p><button onClick={()=>{setStarted(false);setDone(false)}}>Try Again</button></>:<><p>Question {i+1} / {qs.length}</p><h2>{qs[i]?.question}</h2><textarea placeholder="Type your answer here..."></textarea><button className="primary" onClick={()=>i+1===qs.length?setDone(true):setI(i+1)}>Next Question</button></>}</div></section>}
function Modal({modal,form,setForm,close,save}){return <div className="overlay"><div className="modal"><button className="close" onClick={close}><X/></button><h2>{modal==='addTopic'?'Add Topic':modal==='editTopic'?'Update Topic':modal==='addQuestion'?'Add Question':'Update Question'}</h2>{modal.includes('Topic')?<><input placeholder="Topic name" value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/><input placeholder="Icon" value={form.icon||''} onChange={e=>setForm({...form,icon:e.target.value})}/><textarea placeholder="Description" value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></>:<><textarea placeholder="Question" value={form.question||''} onChange={e=>setForm({...form,question:e.target.value})}/><textarea placeholder="Answer" value={form.answer||''} onChange={e=>setForm({...form,answer:e.target.value})}/><select value={form.difficulty||'Medium'} onChange={e=>setForm({...form,difficulty:e.target.value})}><option>Easy</option><option>Medium</option><option>Hard</option></select><select value={form.category||'Interview'} onChange={e=>setForm({...form,category:e.target.value})}><option>Interview</option><option>Coding</option><option>Concept</option><option>Scenario</option><option>Advanced</option></select><input placeholder="Tags" value={form.tags||''} onChange={e=>setForm({...form,tags:e.target.value})}/></>}<button className="primary full" onClick={save}>Save</button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
